In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({"text":["karthik is great",
                         "karthik  like actions",
                         "God loves karthik",
                          "karthik is in love"],"output":[1,1,0,0]})


In [7]:
df.head()

text  output
0       karthik is great       1
1  karthik  like actions       1
2      God loves karthik       0
3     karthik is in love       0

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [9]:
bow=cv.fit_transform(df["text"])

In [13]:
cv.vocabulary_

{'karthik': 5,
 'is': 4,
 'great': 2,
 'like': 6,
 'actions': 0,
 'god': 1,
 'loves': 8,
 'in': 3,
 'love': 7}

In [14]:
bow.toarray()

array([[0, 0, 1, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0]], dtype=int64)

In [15]:
cv.transform(["karthik loves a girl"]).toarray()

array([[0, 0, 0, 0, 0, 1, 0, 0, 1]], dtype=int64)

<h1>N-gram</h1>

In [16]:
df

text  output
0       karthik is great       1
1  karthik  like actions       1
2      God loves karthik       0
3     karthik is in love       0

In [17]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [18]:
bow = cv.fit_transform(df['text'])

In [19]:

print(cv.vocabulary_)

{'karthik is': 4, 'is great': 2, 'karthik like': 5, 'like actions': 6, 'god loves': 0, 'loves karthik': 7, 'is in': 3, 'in love': 1}


In [20]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

<h1>TF-IDF (Term frequency- Inverse document frequency)</h1>


In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid=TfidfVectorizer()

In [22]:
arr= tfid.fit_transform(df["text"]).toarray()

In [23]:
arr

array([[0.        , 0.        , 0.72664149, 0.        , 0.5728925 ,
        0.37919167, 0.        , 0.        , 0.        ],
       [0.66338461, 0.        , 0.        , 0.        , 0.        ,
        0.34618161, 0.66338461, 0.        , 0.        ],
       [0.        , 0.66338461, 0.        , 0.        , 0.        ,
        0.34618161, 0.        , 0.        , 0.66338461],
       [0.        , 0.        , 0.        , 0.58783765, 0.46345796,
        0.30675807, 0.        , 0.58783765, 0.        ]])

In [24]:

print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.51082562 1.
 1.91629073 1.91629073 1.91629073]
